### ISSUE TITLE
orthography issue

### ISSUE THREAD

**Issue by MacyL** [lexibank/chenhmongmien#12]
In the orthography profile: 

^tl | t l
-- | --
^tl | tˡ

which option is a better one?

**Comment by MacyL** [comment]
The same question to 

bl | b l
-- | --
bl | bˡ

And 

pl | p l
-- | --
pl | p ɭ
pl | pˡ

And 


tl | t l
-- | --
tl | tˡ

**Comment by LinguList** [comment]
do you have cases like tliaŋ or similar? the problem is that a) it is
useful to treat -l- as medial (i.e.: t l), but if there's a "tliaŋ", we
would have two medials: l and i (=j). In this case, we may have to add a
"t l_j" to it (_j = j-superskript).

**Comment by MacyL** [comment]
No case like tliang. In fact, tl appears only once, 
|Gloss | Chuanqiandian | Chuanqiandian, Central Guizhou|
|--------|-----------------------|--------------|
|桃      | tsi⁵⁵tlua³¹            | pi¹³tɬa⁵⁵   |


I think tl can be treated as /t l/ according to Chen's consonant table.

I am checking the other cases.

**Comment by MacyL** [comment]
see pull request #13
