### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by MacyL** [lexibank/chenhmongmien#19]
@chrzyki some new commends have been included into this repository, could you make a new release of this repository?

**Comment by MacyL** [comment]
Ah, is it possible to have a zenodo doi, too?

**Comment by chrzyki** [comment]
Sure, I'll do this in the next hour.

**Comment by chrzyki** [comment]
@xrotwang Is it okay if I release this now (minor?) or should I wait for anything else? I'll also fix any buildbot warnings before that if that's okay.

**Comment by LinguList** [comment]
sorry for confusion. Can you please give me some time, so I can add the information on the commands that we added there? 

this is a general question:

We added commands, for our workflow paper, they are not releated to the repository. But we thought it would be useful. yet we should explain them in the NOTES.md

I would like to do that before having a minor release.

**Comment by chrzyki** [comment]
Sure, no problem. :) Just ping me when you're ready.

**Comment by LinguList** [comment]
done now, will need a re-running of the cldfbench.

**Comment by MacyL** [comment]
in the NOTES.md, the dots are missing. Can I edit it?

**Comment by LinguList** [comment]
Yes, please do so.

**Comment by MacyL** [comment]
I made some changes in the NOTES.md, the first command line is cldfbench chenhmongmien.check_structure 
and the rest of the command lines are all correct. 
The outputs are all in a workflow folder.

**Comment by chrzyki** [comment]
Okay, I'll go ahead and rebuild & release then?

**Comment by LinguList** [comment]
Yes, fine by me!

**Comment by chrzyki** [comment]
Done: https://github.com/lexibank/chenhmongmien/releases/tag/v2.1.0

I've also updated the Zenodo record's metadata.

**Comment by MacyL** [comment]
thank you!
