### ISSUE TITLE
[SEALLABLE] Syllable problems

### ISSUE THREAD

**Issue by LinguList** [lexibank/chenhmongmien#22]
# Missing Values                                    

|   Number | Segments     | Structure   |   Examples |
|---------:|:-------------|:------------|-----------:|
|        1 | p ʐ ɑ ³⁵     | i ? ? t     |          4 |
|        2 | z ɦ aɯ ³⁵    | i ? ? t     |          1 |
|        3 | k u æ̃ ⁴⁴     | i n ? t     |          2 |
|        4 | n z u ⁵⁵     | i ? ? t     |          1 |
|        5 | n z õ ⁴²     | i ? ? t     |          1 |
|        6 | ⁿp ʐ ə ¹³    | i ? ? t     |          2 |
|        7 | z ɦ o ¹¹     | i ? ? t     |          1 |
|        8 | n z ɯ ³¹     | i ? ? t     |          1 |
|        9 | p ʐ ei ⁴⁴    | i ? ? t     |          2 |
|       10 | p ɭ ɔ ³²     | i ? ? t     |          2 |
|       11 | ⁿp ʐ u ¹³    | i ? ? t     |          2 |
|       12 | m ʐ ə ⁴²     | i ? ? t     |          2 |
|       13 | ⁿp ʐ æ ⁵³    | i ? ? t     |          1 |
|       14 | m ʐ ɯ ³¹     | i ? ? t     |          3 |
|       15 | ɢ ɦ au ¹¹    | i ? ? t     |          2 |
|       16 | p ʐ u ⁴⁴     | i ? ? t     |          3 |
|       17 | tɕʰ u ẽ ⁵⁵   | i n ? t     |          1 |
|       18 | ⁿp ʐ əu ⁵⁵   | i ? ? t     |          2 |
|       19 | m ʐ ə ⁵³     | i ? ? t     |          1 |
|       20 | m ʐ e ⁵⁵     | i ? ? t     |          1 |
|       21 | ⁿp z i ²⁴    | i ? ? t     |          5 |
|       22 | z ɦ a ¹¹     | i ? ? t     |          1 |
|       23 | ʁ ɹ ɛ ²⁴     | i ? ? t     |          1 |
|       24 | ŋ ɦ u ¹¹     | i ? ? t     |          1 |
|       25 | m ʐ ɛ ³⁵     | i ? ? t     |          2 |
|       26 | z ɦ au ³¹    | i ? ? t     |          2 |
|       27 | p ʐ ə ¹³     | i ? ? t     |          1 |
|       28 | n z ẽ ⁴²     | i ? ? t     |          1 |
|       29 | p ʐ ei ²¹    | i ? ? t     |          1 |
|       30 | ⁿp ʐ e ¹¹    | i ? ? t     |          5 |
|       31 | m ʐ ɯ ²²     | i ? ? t     |          3 |
|       32 | ɢ ɦ ey ³⁵    | i ? ? t     |          1 |
|       33 | ʁ ɹ əu ³³    | i ? ? t     |          1 |
|       34 | ɢ ɦ au ³⁵    | i ? ? t     |          1 |
|       35 | m ʐ ɛ ⁵³     | i ? ? t     |          1 |
|       36 | ⁿp ʐ ɔ ²¹    | i ? ? t     |          1 |
|       37 | p ʐ æ ⁴²     | i ? ? t     |          8 |
|       38 | ⁿʈ ʂ ʅ ¹¹    | i ? ? t     |          1 |
|       39 | p z i ⁵⁵     | i ? ? t     |          7 |
|       40 | p z i ²⁴     | i ? ? t     |          3 |
|       41 | z ɦ a ³⁵     | i ? ? t     |          1 |
|       42 | ⁿb z i ³³    | i ? ? t     |          1 |
|       43 | n z u ⁴²     | i ? ? t     |          1 |
|       44 | ⁿp ʐ ɪ ²¹    | i ? ? t     |          2 |
|       45 | ɢ ɦ ɯ ³⁵     | i ? ? t     |          2 |
|       46 | qʰ ʁ a ⁵⁵    | i ? ? t     |          1 |
|       47 | m ʐ ɑ ⁴²     | i ? ? t     |          1 |
|       48 | k u æ ⁴⁴     | i n ? t     |          5 |
|       49 | p u ẽ ³³     | i n ? t     |          1 |
|       50 | n z ɛ ¹³     | i ? ? t     |          1 |
|       51 | q ʁ ei ²⁴    | i ? ? t     |          3 |
|       52 | ɢ ɦ o ³¹     | i ? ? t     |          2 |
|       53 | p u æ ⁴⁴     | i n ? t     |          1 |
|       54 | ɕʰ u ẽ ¹³    | i n ? t     |          1 |
|       55 | p ʐ ɯ ⁴⁴     | i ? ? t     |          5 |
|       56 | tɕ u ẽ ²²    | i n ? t     |          1 |
|       57 | ts u ã ⁵⁵    | i n ? t     |          1 |
|       58 | ɕ u æ̃ ⁴⁴     | i n ? t     |          1 |
|       59 | k u o ⁴⁴     | i n ? t     |          1 |
|       60 | ɕ u æ̃ ³³     | i n ? t     |          1 |
|       61 | p ʐ ɑ ³¹     | i ? ? t     |          1 |
|       62 | p ʐ a ŋ ³⁵   | i ? n c t   |          1 |
|       63 | z ɦ u ¹¹     | i ? ? t     |          1 |
|       64 | xʰ u æ ⁴⁴    | i n ? t     |          1 |
|       65 | p ʐ a ²²     | i ? ? t     |          1 |
|       66 | pʰ ʐ o ³⁵    | i ? ? t     |          2 |
|       67 | p u æ ³³     | i n ? t     |          2 |
|       68 | d ʐ u ³³     | i ? ? t     |          1 |
|       69 | p ʐ ɔ ⁵³     | i ? ? t     |          1 |
|       70 | ⁿp ʐ e ²²    | i ? ? t     |          1 |
|       71 | ⁿɖ ɦ a ¹¹    | i ? ? t     |          1 |
|       72 | ȵ c ɯ ²²     | i ? ? t     |          1 |
|       73 | p z i ³¹     | i ? ? t     |          4 |
|       74 | p ʐ ei ³⁵    | i ? ? t     |          3 |
|       75 | p ʐ ɿ ³²     | i ? ? t     |          1 |
|       76 | d o          | ? ?         |          1 |
|       77 | p ʐ ɪ ³²     | i ? ? t     |          1 |
|       78 | n z ə̃ ²²     | i ? ? t     |          1 |
|       79 | q ʁ e n ³³   | i ? n c t   |          2 |
|       80 | ɢ ɦ au ³¹    | i ? ? t     |          1 |
|       81 | t u ẽ ³³     | i n ? t     |          1 |
|       82 | p ʐ e ³²     | i ? ? t     |          1 |
|       83 | ⁿɖ ɦ u ³¹    | i ? ? t     |          1 |
|       84 | ɢ ɦ ɯ ¹¹     | i ? ? t     |          1 |
|       85 | h u æ ³²     | i n ? t     |          1 |
|       86 | k u æ̃ ¹³     | i n ? t     |          1 |
|       87 | d ʐ ey ³¹    | i ? ? t     |          1 |
|       88 | l u ẽ ⁵³     | i n ? t     |          1 |
|       89 | v z a ŋ ³¹   | i ? n c t   |          2 |
|       90 | k u æ̃ ⁵⁵     | i n ? t     |          2 |
|       91 | ⁿp ʐ a ³²    | i ? ? t     |          3 |
|       92 | m ʐ o ³⁵     | i ? ? t     |          1 |
|       93 | m ʐ ei ⁴²    | i ? ? t     |          1 |
|       94 | n z ə ¹³     | i ? ? t     |          1 |
|       95 | q ɹ e n ³¹   | i ? n c t   |          1 |
|       96 | n z ɛ ⁴²     | i ? ? t     |          2 |
|       97 | ⁿp ʐ a ŋ ²³² | i ? n c t   |          1 |
|       98 | n z o ²²     | i ? ? t     |          1 |
|       99 | z ɦ a ³¹     | i ? ? t     |          1 |
|      100 | q ɹ a ŋ ²⁴   | i ? n c t   |          1 |
|      101 | m ʐ ei ²²    | i ? ? t     |          1 |
|      102 | q ɹ əu ³³    | i ? ? t     |          1 |
|      103 | p ʐ o ³¹     | i ? ? t     |          2 |
|      104 | n z i ¹³     | i ? ? t     |          1 |
|      105 | n z ə ³¹     | i ? ? t     |          2 |
|      106 | p ʐ o ŋ ²²   | i ? n c t   |          1 |
|      107 | n z o ²⁴     | i ? ? t     |          1 |
|      108 | p ʐ o ²²     | i ? ? t     |          1 |
|      109 | p ʐ a ⁵³     | i ? ? t     |          1 |
|      110 | n z ə ⁴²     | i ? ? t     |          1 |
|      111 | n z ɯ ²²     | i ? ? t     |          1 |
|      112 | ŋ ɦ ɯ ³¹     | i ? ? t     |          1 |
|      113 | ⁿp u/ʐʷ a ⁵³ | i ? ? t     |          1 |
|      114 | m ʐ e ³¹     | i ? ? t     |          1 |
|      115 | q ɹ e ³³     | i ? ? t     |          1 |
|      116 | n z a ²²     | i ? ? t     |          1 |
|      117 | p ʐ a ¹³     | i ? ? t     |          1 |
|      118 | l u æ ⁵⁵     | i n ? t     |          1 |
|      119 | l u æ ²¹     | i n ? t     |          1 |
|      120 | p ʐ o ⁴⁴     | i ? ? t     |          1 |
|      121 | h z a ³³     | i ? ? t     |          1 |
|      122 | ɢ ɦ u ³⁵     | i ? ? t     |          1 |
|      123 | ⁿb z ɿ ³¹    | i ? ? t     |          1 |
|      124 | p z au ³³    | i ? ? t     |          2 |
|      125 | p ʐ ɔ ³⁵     | i ? ? t     |          1 |
|      126 | p ʐ o ⁴²     | i ? ? t     |          1 |
|      127 | m ʐ e n ⁴⁴   | i ? n c t   |          1 |
|      128 | pʰ z i ⁵⁵    | i ? ? t     |          1 |
|      129 | m u          | ? ?         |          1 |
|      130 | p ʐ u ⁵³     | i ? ? t     |          1 |
|      131 | k u æ ¹³     | i n ? t     |          2 |
|      132 | p ʐ ei ⁴²    | i ? ? t     |          1 |
|      133 | v z a ŋ ³³   | i ? n c t   |          1 |
|      134 | m ʐ ə ŋ ¹³   | i ? n c t   |          1 |
|      135 | n z a ¹³     | i ? ? t     |          1 |
|      136 | ˀȵ i         | ? ?         |          1 |
|      137 | tɕ u æ̃ ³³    | i n ? t     |          1 |

**Comment by LinguList** [comment]
A lot of cases are easy to handle if we only add the medials to the list (should be shared here, separated by comma). But other cases need to be handled in the orthoprofile, e.g., missing tones, and the like, or "uæ", where "u" should be "u/w".

**Comment by MacyL** [comment]
I updated the orthography profile. My command-line:
`cldfbench lexitools.seallable lexibank_chenhmongmien.py --medials=l,z,ɹ,r,ʐ,ʐʷ,w,j,ɥ,ɭ,lʲ,ʁ,lʷ,c`
