### ISSUE TITLE
Maybe add the "first form only" argument in the script?

### ISSUE THREAD

**Issue by MacyL** [lexibank/chenhmongmien#31]
When I work on annotating the congates, I realize that there are some duplicated words for the same concepts and languages. For example  the concept "wake up". 

Should we add the "first form only" argument in the script to prevent the duplicated entries?

**Comment by LinguList** [comment]
I do not think they are duplicated, there are rather synonymous forms.

**Comment by MacyL** [comment]
I agree that they are synonymous forms, but I think the synonymous forms cause the trouble when it comes to cognate annotation.
![Screenshot 2020-09-04 at 11 19 37](https://user-images.githubusercontent.com/19792535/92223279-87dff180-eea0-11ea-9deb-6b2e8abd21c8.png)
Should we leave these in the data, or remove them?

**Comment by LinguList** [comment]
Yes, this is an issue for the evaluation, not for the CLDF dataset: when writing "remove", please write "!remove!" instead.

**Comment by MacyL** [comment]
I see. Then I close this issue for now.
