### ISSUE TITLE
[Task] Morphemes information

### ISSUE THREAD

**Issue by Wu-Urbanek** [lexibank/chenhmongmien#32]
please see the `morphemes.tsv` in the `etc/` folder in the new branch `msw_grammarticalmorphemes`. 

I set up three columns as the starting point.

**Comment by LinguList** [comment]
Okay, you have this one:

```
Language_ID	Tokens	Morphemes
EasternLuobuohe	pə⁰⁵	-affix
EasternLuobuohe	tə⁰²	-affix
EasternLuobuohe	qo⁰⁵	-affix
EasternLuobuohe	ʔa⁰²	-affix
```

But what I want is:

Language_ID     | Form | Tokens  | Position | Type  | Gloss | ShortName
---             | ---  | ---     | ---      | ---   | --- | ---
EasternLuobuohe | pə⁰⁵ | p ə ⁰/⁵ | ^        | affix | ? | pə
EasternLuobuohe | tə⁰² | t ə ⁰/⁵ | ^        | affix | ? | tə
EasternLuobuohe | qo⁰⁵ | q o ⁰/⁵ | ^        | affix | ? | qo
EasternLuobuohe | ʔa⁰² | ʔ a ⁰/² | ^        | affix | ? | ʔa

**Comment by LinguList** [comment]
If position is empty, it can appear everywhere. If you use $, it means: at the end of a word.

In this way, we can create an automated gloss from the data:

Language_ID     | Form | Tokens  | Position | Type  | Gloss | ShortName |EDICTOR
---             | ---  | ---     | ---      | ---   | --- | --- | ---
EasternLuobuohe | pə⁰⁵ | p ə ⁰/⁵ | ^        | A | ? | pə | ?:A.^/pə
EasternLuobuohe | tə⁰² | t ə ⁰/⁵ | ^        | A | ? | tə | ?:A.^/tə
EasternLuobuohe | qo⁰⁵ | q o ⁰/⁵ | ^        | A | ? | qo | ?:A.^/qo
EasternLuobuohe | ʔa⁰² | ʔ a ⁰/² | ^        | A | ? | ʔa | ?:A.^/ʔa

**Comment by LinguList** [comment]
So, @MacyL, this translates to the following rules for naming a morpheme in a word form:

1. it needs at least one name expressing the concept that is expressed (which can be a question mark)
2. if a `:` follows, this will give the name for the type (affix, noun, verb, 2.PL)
3. if a `/` follows, this gives a short name we want to use for the morpheme, like "tə-affix". 

This should be consistent enough for our purposes. 

I started working this into the EasternLuobuohe data, but I used "^" as well, yet, if you want to, @MacyL, you could update this for the four items. You only need to filter, and could then add the names for the affixes in morphemes.

**Comment by LinguList** [comment]
Update, what about this?

Language_ID     | Form | Tokens  | Meaning | Position | Type  | Gloss | ShortName | EDICTOR
---             | ---  | ---     | --- | ---      | ---   | --- | --- | ---
EasternLuobuohe | pə⁰⁵ | p ə ⁰/⁵ | syn | ^        | Aff | ? | pə | -?:Aff/pə
EasternLuobuohe | tə⁰² | t ə ⁰/⁵ | syn | ^        | Aff | ? | tə | -?:Aff/tə
EasternLuobuohe | qo⁰⁵ | q o ⁰/⁵ | syn | ^        | Aff | ? | qo | -?:Aff/qo
EasternLuobuohe | ʔa⁰² | ʔ a ⁰/² | syn | ^        | Aff | ? | ʔa | -?:Aff/ʔa
EasternLuobuohe |      | ʔ u ŋ ³¹ | auto |  | | WATER |  | WATER

**Comment by LinguList** [comment]
You see, @MacyL, we can use this also as our later goal to provide a detailed explanation of all of the data by morphemes, once we have annotated them.

**Comment by LinguList** [comment]
You could go ahead and annotate those already in edictor now. Then we see how this works and go for the next language. BTW: any dettails by Chén on the specific meaning of the affixes?

**Comment by MacyL** [comment]
I do not understand why there is a `ʔ u ŋ ³¹` water? `ʔuŋ³¹` is not a prefix in this language.

**Comment by MacyL** [comment]
Also, sometimes the affixes have meanings, but sometimes the affixes have no meaning at all. It depends on the language. 
I understand the purpose of "Meaning" column. But if you have time, can you also explain what the "Gloss" is?

**Comment by LinguList** [comment]
Sorry, Mei-Shin, this means WATER, we do not only talk about prefixes,
we talk about known morphemes, I added WATER to show how the code will
render this, if no information on the other parts is given ;)

**Comment by LinguList** [comment]
syn = synsemantic, this means, the morpheme cannot exist alone (think of "zi" in many cases in Chinese with zero tone). auto = autosemantic, this means, the morpheme can occur on its own. The conversion to EDICTOR will, if something cannot exist on its own, add a `-`, to indicate the affix nature (but it's not only affix, but also verbal endings, etc.)

**Comment by LinguList** [comment]
Note that we may have to change parts here, I am not yet really sure of how to annotate everything, but basically, the chart could be automatically re-generated from taking our annotations in EDICTOR and imposing it on the words in the dataset. Just for example.

**Comment by MacyL** [comment]
I see, the direction of the approach between us is a bit different. Your approach is to summary the words that's occurring in the data and then annotate each one of them separately.
I was suggesting that we firstly collect all the "affix" information from the book, and then we use this information to (automatically-)annotate the data. 
My reason is that the "affix" will appear in various words many times through the data, but affix information or even some particularly important morphemes like "month" or "car", etc, will be mentioned in the book like a summary. Once we have this information as a `.tsv` file, we can write a script to annotate the data. I understand that we sooner or later have to go through the dataset on Edictor, but if the repetitive task can be reduced, the less inconsistency will be occurred, right?

**Comment by MacyL** [comment]
But I agree with the **syn** and **auto** marking, that's a very good scheme to follow when I go through the book and set up the list. Thanks for suggesting this one.

**Comment by LinguList** [comment]
@MacyL, we are not in different directions, you do not see the consequences of my approach, which is including yours.

**Comment by LinguList** [comment]
My approach is:

1. **Goal**: set up a table of all unique morphemes for each language, ideally also with a plugin in EDICTOR, so we can check them.
2. **How to get there**: we can define productive affixes in the schema above and then apply them to a given language, but then, we need to manually annotate the data, and essentially, the annotation that we use to annotate the data automatically is equivalent to what we can pull out from the data, so we have clear code in both directions.

To put it in other words:

* given a wordlist with perfectly annotated morphemes, following a schema we agree on, we should extract the table I showed to you automatically
* given the table and a wordlist without morphemes, we should be able to add the morphemes to the wordlist

I am thinking about consistent code that allows for a uniform annotation that could happen manually, but also independently, by using another sheet.

**Comment by MacyL** [comment]
From your direction, this is how I understand (to put it in a practice): 
1. firstly extract the morphemes per language according to the morphemes we already annotated last time. (i.e. a "morpheme summary" table) 
2. I check the book an go through the summary table and change the annotation (the Meaning column)? 
For example : 
1) data on Edictor

| word form     |Gloss    | morphemes (automatic detection + I modified two weeks ago)|
|--------------|---------|------------|
| qo⁰⁵me³¹        |  INK       |    ink  INK  |
| qo⁰⁵ʔuŋ³¹     (assume there is this word)   |  WATER |  water  WATER |

2) a code to extract and form a summary table (in the form you suggested)

|Language_ID | Form | Tokens| Meaning (I annotate) | Gloss|
|-------------| ------| --------| ---------| ----|
|EasternLuobuohe| qo⁰⁵ | q o ⁰/⁵| syn| affix|
|EasternLuobuohe| me³¹  | m e ³¹ | auto|INK| 
|EasternLuobuohe| ʔuŋ³¹  | ʔ u ŋ ³¹ | auto|WATER| 

3) Apply back to Edictor or to another dataset

**Comment by LinguList** [comment]
Not exactly. I was merely explaining the annotation, the example of WATER was just an example. So for the morpheme tables, it is enough to take the examples from the book, that is, not WATER, but WATER was an example of how a noun WOULD be annotated.

So the workflow is still:

1. read the book and extract per language, add this to our `morphemes` in etc., but try to also add some info regarding the specific meaning (Gloss) of the prefix or suffix. 
2. apply this to the data and modify the morphemes accordingly (either automatically, or manually, in fact, it does not take much time to annotate 60 prefixes with edictor now).

**Comment by MacyL** [comment]
Now it's much clear to me. Thanks for clarify :)

**Comment by LinguList** [comment]
So I'd say, @MacyL, you could start doing the annotation as discussed above **manually** for luobuohe, and then you search for another example. Note that the column EDICTOR in my example is what should be written in EDICTOR.

**Comment by MacyL** [comment]
Ok, will send you a notification once I update the file.

**Comment by MacyL** [comment]
Please have a look at the newly uploaded [file](https://github.com/lexibank/chenhmongmien/blob/msw_grammarticalmorphemes/etc/morphemes.tsv)

I add three languages. There are more examples in the book, the entries in the files are only a small portion of them (this file is an example). And my questions are : 
1. Entry 10 : 抱 does not have a concepticon gloss, should I still include it? 

2. Entry 7, 13, and etc : Only lists the morphemes (字) in the `Form` column, is it correct? Take the entry 13 "DAY" as an example, the wordlist data entry is [qo⁰⁵ŋɢwaŋ³¹](https://github.com/lexibank/chenhmongmien/blob/master/raw/raw.csv)  , in the section of Eastern Luobuohe language, Chen shows that the `ŋɢwaŋ³¹` is the morpheme (字) and the meaning is 天空(sky).  

3. Entry 18 : `ʔə⁰⁵` is used before the quantifiers, and `ʔə⁰²` is another affix. To separate them, I put `ʔə⁰⁵` as the ShortName of `ʔə⁰⁵` and `ʔə` as the ShortName of `ʔə⁰²`. 

4. Entry 19-23. Chuanqiandian language is not included in the Edictor dataset, should I include the information about this language? 

5. The Remark column, it contains the usage of the affix or the "regular morpheme" (auto).  I do not know if this information are important to our analysis, so I added it.

**Comment by LinguList** [comment]
This is very nice, thanks, @macyl, we need to refine the remarks (it
should be "appear**s**, not "appear"), but otherwise this is what I
wanted: to show all the valid information which we can find already in
the book. We may think of additional names, like "-quantifer:Affix" or
"-adj:Affix", based on the appearance, you see? In this way, we can also
try to unify things. This would mean: you write something like "adj"
into the GLOSS field.


Include whatever language you can find, this is generally useful work.

**Comment by MacyL** [comment]
I see. I will modify accordingly, thanks!

**Comment by FredericBlum** [comment]
@LinguList What is the status on this dataset?
