### ISSUE TITLE
fix bookkeeping language 

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/chenhmongmien#9]
https://glottolog.org/resource/languoid/id/chua1256

**Comment by SimonGreenhill** [comment]
should be "Dananshan Miao"?

**Comment by LinguList** [comment]
That does not seem to be so clear. @MacyL, what further hints on that variety did you find in the text?

**Comment by SimonGreenhill** [comment]
@MacyL  -- any ideas what this could be?

**Comment by MacyL** [comment]
it's chua1248 (Chuanqiandian), i will fix it now

**Comment by MacyL** [comment]
fixed, thanks for pointing it out.

**Comment by SimonGreenhill** [comment]
Awesome, thanks for fixing it :)
